### ISSUE TITLE
feat: add iOS support

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-managed-configurations#4]
**Is your feature request related to a problem? Please describe:**

iOS is currently not supported.

**Describe the solution you'd like:**

Add iOS support.

**Describe alternatives you've considered:**

**Additional context:**

https://stackoverflow.com/questions/20752254/using-mdm-to-configure-an-enterprise-app-via-nsuserdefaults

**Comment by petarov** [comment]
Hi, I noticed the README says:

> The iOS implementation could not be tested yet. I appreciate any feedback.

Just wanted to provide some feedback that the plugin works on iOS. I've tested it on the Simulator as well as on iPhone and iPad devices. I got a small app published using this plugin. 

Thanks a lot! 🍻

**Comment by robingenz** [comment]
@petarov That's awesome! Thank you for letting me know.
